name: build and deploy

on:
  push:
  pull_request:

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.build.outputs.out_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM (api → client/src/wasm)
        id: build
        working-directory: api
        run: |
          mkdir -p ../client/src/wasm
          wasm-pack build \
            --release \
            --target web \
            --out-dir ../client/src/wasm
          echo "::set-output name=out_dir::$(pwd)/../client"

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client
          publish_branch: gh-pages
          force_orphan: true
  
